// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK5CG9wuG3ldRPaD1R-9I28o6wNgcNHbc',
    appId: '1:921194076041:web:8e48c5b6caf3736f423358',
    messagingSenderId: '921194076041',
    projectId: 'lueur-app-d6c35',
    authDomain: 'lueur-app-d6c35.firebaseapp.com',
    storageBucket: 'lueur-app-d6c35.firebasestorage.app',
    measurementId: 'G-Z18CQ3QZ7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt-HxsiXXy36wXHPD4EBsRr8eWZEJmha8',
    appId: '1:921194076041:android:6966d24fa919db01423358',
    messagingSenderId: '921194076041',
    projectId: 'lueur-app-d6c35',
    storageBucket: 'lueur-app-d6c35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYIm_TJSmmdoJwPhC3vxlecpAKoZBm7FU',
    appId: '1:921194076041:ios:3394aebd6952b077423358',
    messagingSenderId: '921194076041',
    projectId: 'lueur-app-d6c35',
    storageBucket: 'lueur-app-d6c35.firebasestorage.app',
    iosClientId: '921194076041-7bmcshushphutf0cqpqojso0dc08pcsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiTherapistApp',
  );
}
