#!/usr/bin/env python3
"""Generate the Lueur Google Play Feature Graphic (1024x500).

Composition: a small, deliberate stack of phones in the exact same frame
style as the store screenshots (thin dark bezel, inset punch-hole camera,
home indicator), plus a compact logo lockup + descriptive tagline in the
top-left, and two small "floating UI" cards — a row of 5 real mood entries
and a 3-stage plant-growth streak — that echo the app's actual journal and
plant features, alongside Luna herself peeking in as a mascot accent. All
on a soft light lavender-to-pink gradient. Rendered at 4x supersample and
LANCZOS-downsampled to the final 1024x500 for crisp edges.

Every visual element here is either a real screenshot (via the phone-frame
renderer below), the real app icon, real mood illustrations, the real Luna
character art, or a real (cropped) plant illustration — no invented
clip-art.
"""

import os

from PIL import Image, ImageDraw, ImageFont, ImageFilter

import generate_store_screenshots as gss

# Own supersample factor, decoupled from gss.SCALE (which the store
# screenshots render at) so it can be raised independently for a sharper
# final downsample without touching the store-screenshot pipeline. Higher
# than gss.SCALE gives LANCZOS more source detail to resolve edges/text
# from when shrinking down to the fixed 1024x500 output.
SCALE = gss.SCALE * 2
FINAL_W, FINAL_H = 1024, 500
W, H = FINAL_W * SCALE, FINAL_H * SCALE

ICON_PATH = os.path.join(gss.OUT_DIR, "lueur_icon_512x512.png")
OUT_PATH = os.path.join(gss.OUT_DIR, "feature-graphic-1024x500.png")
MASTER_OUT_PATH = os.path.join(gss.OUT_DIR, f"feature-graphic-{W}x{H}.png")
ILLUSTRATIONS_DIR = os.path.join(gss.ROOT, "assets", "illustrations")
LUNA_PATH = os.path.join(gss.ROOT, "assets", "images", "luna_splash.png")
PLANT_PATH = os.path.join(gss.OUT_DIR, "plant_grown.png")

# Flatter, thinner frame than the store screenshots use — the feature
# graphic's small cascade of phones reads better with a more rectangular
# silhouette and a thinner border than the full-size store screenshots
# (gss.FRAME_CORNER_R / gss.BEZEL_WIDTH), so these are overridden locally
# only for this script; the shared constants (and the store screenshots
# they produce) are left untouched. Expressed per-unit (constant / gss.SCALE)
# and rescaled by this script's own SCALE so the ratio holds regardless of
# how the two supersample factors diverge.
PHONE_FRAME_CORNER_R = round((gss.FRAME_CORNER_R / gss.SCALE) * 0.28 * SCALE)
PHONE_FRAME_BEZEL_WIDTH = round((gss.BEZEL_WIDTH / gss.SCALE) * 0.45 * SCALE)

TAGLINE = "Mood, journaling & calm"
DESCRIPTION = "Check in with how you feel, chat it through with Luna, and watch your calm grow, one small day at a time."

# Soft, light lavender-to-pink gradient — much airier than the deep-purple
# brand gradient used elsewhere, to match the reference's pastel backdrop.
GRADIENT_LEFT = (0xE9, 0xE1, 0xF9)
GRADIENT_RIGHT = (0xF6, 0xE3, 0xEC)

# Three framed phones, from back to front. The source screens are all taken
# from store1; the frame itself is generated by the same renderer that makes
# the Play Store screenshot set, ensuring the bezel, punch-hole, buttons and
# home indicator match exactly.
PHONE_SCREENS = [
    # Three phones, not four — dropping one lets the remaining three grow
    # substantially (h_frac 0.50 -> 0.72) while still fitting, fanned, in
    # the ~500px-wide column right of the logo/cards, so the screenshot UI
    # inside each is actually legible at the graphic's normal display size.
    # Home (bold emoji capture) and Breathing (a big, simple guided circle)
    # both read cleanly at a glance; Journal's list/chart is comparatively
    # dense and is dropped in its favour (journaling is still represented
    # by the "This week's check-ins" card below). Chat/Luna is the hero
    # feature and stays largest-reading by being drawn last, on top, with
    # the boldest fan angle. Same tilted-fan cascade as before, just three
    # wide instead of four.
    {"screenshot": "home_light.png", "angle": -6, "h_frac": 0.72, "cx_frac": 0.530, "cy_frac": 0.535},
    {"screenshot": "breathing_light.png", "angle": 0, "h_frac": 0.72, "cx_frac": 0.700, "cy_frac": 0.495},
    {"screenshot": "chat_with_ai_luna_more_dark.png", "angle": 6, "h_frac": 0.72, "cx_frac": 0.868, "cy_frac": 0.535, "wifi_icon": True},
]

# Five real mood entries (Journal-style), shown as a small floating card —
# reads as "a real, lived-in app" rather than an empty mockup.
MOOD_ROW = ["happy", "grateful", "calm", "hopeful", "excited"]

# Three growth stages of the same real plant illustration, scaled up in a
# row — a lightweight nod to the streak/plant feature.
PLANT_STAGE_SCALES = [0.42, 0.68, 1.0]


def horizontal_gradient(width, height, left_rgb, right_rgb):
    base = Image.new("RGB", (width, 1), 0)
    for x in range(width):
        t = x / max(width - 1, 1)
        r = round(left_rgb[0] + (right_rgb[0] - left_rgb[0]) * t)
        g = round(left_rgb[1] + (right_rgb[1] - left_rgb[1]) * t)
        b = round(left_rgb[2] + (right_rgb[2] - left_rgb[2]) * t)
        base.putpixel((x, 0), (r, g, b))
    return base.resize((width, height), Image.Resampling.NEAREST)


def draw_living_background(canvas):
    """Layer soft organic colour and small growth-like accents behind the
    content. They give the calm/journaling concept some life without ever
    competing with the product screens or legibility of the store copy."""
    glow = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    glow_draw = ImageDraw.Draw(glow)

    # Large, diffused brand-colour pools make the otherwise flat pastel
    # background feel warm and dimensional.
    glow_draw.ellipse(
        (-250 * SCALE, -210 * SCALE, 330 * SCALE, 290 * SCALE),
        fill=(0xC8, 0xB4, 0xF8, 115),
    )
    glow_draw.ellipse(
        (560 * SCALE, -190 * SCALE, 1120 * SCALE, 310 * SCALE),
        fill=(0x5B, 0xBF, 0xA0, 92),
    )
    glow_draw.ellipse(
        (240 * SCALE, 300 * SCALE, 810 * SCALE, 690 * SCALE),
        fill=(0xE8, 0x82, 0x5A, 60),
    )
    glow = glow.filter(ImageFilter.GaussianBlur(70 * SCALE))
    canvas.alpha_composite(glow)

    accents = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    accent_draw = ImageDraw.Draw(accents)
    # A few quiet seed/leaf marks reinforce the app's small-daily-growth
    # idea. Kept to empty areas and rendered at low opacity.
    for x, y, r, color in [
        (374, 54, 5, (0x5B, 0xBF, 0xA0, 110)),
        (416, 75, 3, (0xE8, 0x82, 0x5A, 100)),
        (341, 428, 4, (0xC8, 0xB4, 0xF8, 130)),
        (434, 448, 3, (0x5B, 0xBF, 0xA0, 105)),
        (974, 69, 4, (0xE8, 0x82, 0x5A, 95)),
    ]:
        accent_draw.ellipse(
            ((x - r) * SCALE, (y - r) * SCALE, (x + r) * SCALE, (y + r) * SCALE),
            fill=color,
        )

    # Simple paired leaves, placed only in open corners.
    for x, y, angle in [(412, 403, 1), (962, 445, -1)]:
        accent_draw.ellipse(
            ((x - 11) * SCALE, (y - 4) * SCALE, x * SCALE, (y + 4) * SCALE),
            fill=(0x5B, 0xBF, 0xA0, 95),
        )
        accent_draw.ellipse(
            (x * SCALE, (y - 4) * SCALE, (x + 11) * SCALE, (y + 4) * SCALE),
            fill=(0x5B, 0xBF, 0xA0, 95),
        )
    canvas.alpha_composite(accents)


def build_soft_shadow(w, h, radius, blur, color):
    pad = blur * 2
    shadow = Image.new("RGBA", (w + pad * 2, h + pad * 2), (0, 0, 0, 0))
    ImageDraw.Draw(shadow).rounded_rectangle(
        [(pad, pad + blur // 3), (pad + w, pad + h + blur // 3)],
        radius=radius,
        fill=color,
    )
    return shadow.filter(ImageFilter.GaussianBlur(blur)), pad


def build_icon_badge(size_px):
    icon = Image.open(ICON_PATH).convert("RGBA").resize((size_px, size_px), Image.Resampling.LANCZOS)
    mask = gss.rounded_mask((size_px, size_px), round(size_px * 0.22))
    badge = Image.new("RGBA", (size_px, size_px), (0, 0, 0, 0))
    badge.paste(icon, (0, 0), mask)
    return badge


def autocrop(im):
    bbox = im.getbbox()
    return im.crop(bbox) if bbox else im


def build_rounded_card(w, h, radius, fill=(255, 255, 255, 235)):
    card = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    ImageDraw.Draw(card).rounded_rectangle([(0, 0), (w - 1, h - 1)], radius=radius, fill=fill)
    return card


def draw_phone(canvas, entry):
    """Place a real store1 capture inside the exact store phone frame."""
    frame_h = round(H * entry["h_frac"])
    path = os.path.join(gss.SOURCE_DIR, entry["screenshot"])
    frame, _, shadow, shadow_pad = gss.build_phone_frame(
        path,
        0,
        frame_h,
        erase_blob=True,
        wifi_icon=entry.get("wifi_icon", False),
        corner_r=PHONE_FRAME_CORNER_R,
        bezel_w=PHONE_FRAME_BEZEL_WIDTH,
    )

    angle = entry["angle"]
    frame_rot = frame.rotate(angle, expand=True, resample=Image.BICUBIC)
    shadow_rot = shadow.rotate(angle, expand=True, resample=Image.BICUBIC)

    cx = round(W * entry["cx_frac"])
    cy = round(H * entry["cy_frac"])

    shadow_x = cx - shadow_rot.width // 2
    shadow_y = cy - shadow_rot.height // 2 + 14 * SCALE
    canvas.alpha_composite(shadow_rot, (shadow_x, shadow_y))

    frame_x = cx - frame_rot.width // 2
    frame_y = cy - frame_rot.height // 2
    canvas.alpha_composite(frame_rot, (frame_x, frame_y))


def draw_phone_cascade(canvas):
    for entry in PHONE_SCREENS:
        draw_phone(canvas, entry)


# Soft pastel chip backgrounds behind each mood icon in the "recent moods"
# card, echoing the mood colours used in the real Journal feature.
MOOD_CHIP_BG = {
    "happy": (0xFD, 0xE6, 0xAE, 255),
    "grateful": (0xF6, 0xCE, 0xDA, 255),
    "calm": (0xCE, 0xE9, 0xE1, 255),
    "hopeful": (0xE3, 0xDF, 0xF7, 255),
    "excited": (0xFB, 0xD2, 0xBE, 255),
}


def draw_mood_entries_card(canvas, draw, x, y):
    """A small floating card echoing the real Journal screen: a row of 5
    real mood entries, each its own pastel chip — makes the graphic read
    as "a real, lived-in app" instead of an empty mockup."""
    label = "This week's check-ins"
    label_font = ImageFont.truetype(gss.BODY_FONT_PATH, 15 * SCALE)

    chip_d = 46 * SCALE
    gap = 14 * SCALE
    pad_x = 18 * SCALE
    pad_top = 14 * SCALE
    label_gap = 8 * SCALE

    label_bbox = draw.textbbox((0, 0), label, font=label_font)
    label_h = label_bbox[3] - label_bbox[1]

    card_w = pad_x * 2 + len(MOOD_ROW) * chip_d + (len(MOOD_ROW) - 1) * gap
    card_h = pad_top * 2 + label_h + label_gap + chip_d

    shadow, shadow_pad = build_soft_shadow(
        round(card_w * 0.94), round(card_h * 0.5), 18 * SCALE, 14 * SCALE, (0x2B, 0x21, 0x38, 60)
    )
    shadow_x = x + card_w // 2 - shadow.width // 2
    shadow_y = y + card_h - shadow.height // 2 - shadow_pad // 2
    canvas.alpha_composite(shadow, (shadow_x, shadow_y))

    card = build_rounded_card(round(card_w), round(card_h), 22 * SCALE)
    canvas.alpha_composite(card, (x, y))

    draw.text((x + pad_x, y + pad_top), label, font=label_font, fill=(0x4A, 0x3A, 0x60, 255))

    chip_y = y + pad_top + label_h + label_gap
    for i, mood in enumerate(MOOD_ROW):
        chip_x = x + pad_x + i * (chip_d + gap)
        bg = MOOD_CHIP_BG.get(mood, (0xEE, 0xEA, 0xF7, 255))
        chip_bg = Image.new("RGBA", (chip_d, chip_d), (0, 0, 0, 0))
        ImageDraw.Draw(chip_bg).ellipse([(0, 0), (chip_d - 1, chip_d - 1)], fill=bg)
        canvas.alpha_composite(chip_bg, (chip_x, chip_y))

        icon = autocrop(Image.open(os.path.join(ILLUSTRATIONS_DIR, f"{mood}.png")).convert("RGBA"))
        icon_size = round(chip_d * 0.72)
        icon = icon.resize((icon_size, icon_size), Image.Resampling.LANCZOS)
        canvas.alpha_composite(
            icon, (chip_x + (chip_d - icon_size) // 2, chip_y + (chip_d - icon_size) // 2)
        )

    return card_w, card_h


def draw_plant_growth_card(canvas, draw, x, y):
    """A second small floating card showing the same real plant
    illustration at three growth sizes, bottom-aligned in a row — a
    lightweight nod to the streak feature growing day by day."""
    label = "Your streak, growing"
    label_font = ImageFont.truetype(gss.BODY_FONT_PATH, 15 * SCALE)
    label_bbox = draw.textbbox((0, 0), label, font=label_font)
    label_w = label_bbox[2] - label_bbox[0]
    label_h = label_bbox[3] - label_bbox[1]

    plant = autocrop(Image.open(PLANT_PATH).convert("RGBA"))
    plant_aspect = plant.width / plant.height

    row_h = 58 * SCALE
    gap = 16 * SCALE
    pad_x = 18 * SCALE
    pad_top = 14 * SCALE
    pad_bottom = 10 * SCALE
    label_gap = 8 * SCALE

    stage_imgs = []
    for scale in PLANT_STAGE_SCALES:
        stage_h = round(row_h * scale)
        stage_w = round(stage_h * plant_aspect)
        stage_imgs.append(plant.resize((stage_w, stage_h), Image.Resampling.LANCZOS))

    row_w = sum(im.width for im in stage_imgs) + gap * (len(stage_imgs) - 1)
    card_w = pad_x * 2 + max(row_w, label_w)
    card_h = pad_top + label_h + label_gap + row_h + pad_bottom

    shadow, shadow_pad = build_soft_shadow(
        round(card_w * 0.94), round(card_h * 0.5), 18 * SCALE, 14 * SCALE, (0x2B, 0x21, 0x38, 60)
    )
    shadow_x = x + card_w // 2 - shadow.width // 2
    shadow_y = y + card_h - shadow.height // 2 - shadow_pad // 2
    canvas.alpha_composite(shadow, (shadow_x, shadow_y))

    card = build_rounded_card(round(card_w), round(card_h), 22 * SCALE)
    canvas.alpha_composite(card, (x, y))

    draw.text((x + pad_x, y + pad_top), label, font=label_font, fill=(0x4A, 0x3A, 0x60, 255))

    # Center the plant row as a group within the card's available width
    # (the 3 plants grow left-to-right, so their combined width isn't
    # symmetric on its own — the row itself needs centering, not each plant).
    available_w = max(row_w, label_w)
    row_start_x = x + pad_x + (available_w - row_w) // 2

    row_y_baseline = y + pad_top + label_h + label_gap + row_h
    cursor_x = row_start_x
    for im in stage_imgs:
        canvas.alpha_composite(im, (cursor_x, row_y_baseline - im.height))
        cursor_x += im.width + gap

    return card_w, card_h


def draw_luna_accent(canvas, card_x, card_w, card_bottom, card_h):
    """Luna herself, peeking in as a friendly mascot accent sized and
    bottom-aligned against the "Your streak, growing" card next to her —
    sized to slightly exceed that card's height so she reads as
    intentionally placed rather than an afterthought."""
    luna = autocrop(Image.open(LUNA_PATH).convert("RGBA"))
    target_h = round(card_h * 0.85)
    target_w = round(target_h * luna.width / luna.height)
    luna = luna.resize((target_w, target_h), Image.Resampling.LANCZOS)
    luna_rot = luna.rotate(-6, expand=True, resample=Image.BICUBIC)

    # Sit just to the right of the card, bottom-aligned with it.
    gap = 16 * SCALE
    luna_x = card_x + card_w + gap
    luna_y = card_bottom - luna_rot.height
    cx = luna_x + luna_rot.width // 2
    cy = luna_y + luna_rot.height // 2

    shadow_w = round(target_w * 0.75)
    shadow_h = round(target_w * 0.22)
    shadow, shadow_pad = build_soft_shadow(
        shadow_w, shadow_h, round(shadow_h * 0.5), 10 * SCALE, (0x2B, 0x21, 0x38, 80)
    )
    shadow_x = cx - shadow.width // 2
    shadow_y = card_bottom - shadow_h // 2 - shadow_pad
    canvas.alpha_composite(shadow, (shadow_x, shadow_y))

    canvas.alpha_composite(luna_rot, (luna_x, luna_y))


def draw_logo_lockup(canvas, draw):
    """Compact icon + wordmark + tagline in the top-left — modest in size
    and clearly secondary to the hero phone."""
    edge_pad = 36 * SCALE
    icon_size = 56 * SCALE

    icon_x = edge_pad
    icon_y = edge_pad
    icon_badge = build_icon_badge(icon_size)
    shadow_w = round(icon_size * 0.75)
    shadow_h = round(icon_size * 0.22)
    shadow, shadow_pad = build_soft_shadow(
        shadow_w, shadow_h, round(shadow_h * 0.5), 8 * SCALE, (0x1E, 0x16, 0x2A, 90)
    )
    shadow_x = icon_x + icon_size // 2 - shadow.width // 2
    shadow_y = icon_y + icon_size - shadow_h // 2 - shadow_pad
    canvas.alpha_composite(shadow, (shadow_x, shadow_y))
    canvas.alpha_composite(icon_badge, (icon_x, icon_y))

    text_x = icon_x + icon_size + round(16 * SCALE)
    wordmark_size = 46 * SCALE
    wordmark_font = ImageFont.truetype(gss.HEADLINE_FONT_PATH, wordmark_size)
    wordmark_cy = icon_y + icon_size // 2
    draw.text((text_x, wordmark_cy), "Lueur", font=wordmark_font, fill=(0x1A, 0x1A, 0x1A, 255), anchor="lm")

    tagline_font = ImageFont.truetype(gss.BODY_FONT_PATH, 17 * SCALE)
    tagline_y = icon_y + icon_size + round(20 * SCALE)
    draw.text((icon_x, tagline_y), TAGLINE, font=tagline_font, fill=(0x4A, 0x3A, 0x60, 255), anchor="lm")

    # A short descriptive line under the tagline, so the graphic actually
    # explains the app idea rather than just naming it.
    desc_font = ImageFont.truetype(gss.BODY_FONT_PATH, 15 * SCALE)
    desc_max_width = 372 * SCALE
    desc_lines = gss.wrap_text(draw, DESCRIPTION, desc_font, desc_max_width)
    ascent, descent = desc_font.getmetrics()
    desc_line_h = round((ascent + descent) * 1.18)
    desc_y = tagline_y + round(30 * SCALE)
    for line in desc_lines:
        draw.text((icon_x, desc_y), line, font=desc_font, fill=(0x5A, 0x4E, 0x70, 255), anchor="lm")
        desc_y += desc_line_h

    return icon_x, desc_y + round(10 * SCALE)


def render():
    canvas = horizontal_gradient(W, H, GRADIENT_LEFT, GRADIENT_RIGHT).convert("RGBA")
    draw_living_background(canvas)
    draw_phone_cascade(canvas)
    draw = ImageDraw.Draw(canvas)
    col_x, cards_y = draw_logo_lockup(canvas, draw)

    mood_card_w, mood_card_h = draw_mood_entries_card(canvas, draw, col_x, cards_y)
    plant_card_y = cards_y + mood_card_h + round(14 * SCALE)
    plant_card_w, plant_card_h = draw_plant_growth_card(canvas, draw, col_x, plant_card_y)

    # Drawn last (on top) and positioned relative to the card column, now
    # that its geometry is known — sits cleanly beside it (clearing the
    # wider of the two cards) instead of floating disconnected or
    # overlapping the mood card above.
    col_w = max(mood_card_w, plant_card_w)
    draw_luna_accent(canvas, col_x, col_w, plant_card_y + plant_card_h, plant_card_h)

    # Keep a 4× RGB master for future artwork use, then downsample the
    # upload-ready file to Google Play's required 1024×500 dimensions.
    master = canvas.convert("RGB")
    master.save(MASTER_OUT_PATH, "PNG")
    final = master.resize((FINAL_W, FINAL_H), Image.Resampling.LANCZOS)
    final.save(OUT_PATH, "PNG")
    print(f"saved {MASTER_OUT_PATH} ({master.width}x{master.height})")
    print(f"saved {OUT_PATH} ({final.width}x{final.height})")


def main():
    os.makedirs(gss.OUT_DIR, exist_ok=True)
    render()


if __name__ == "__main__":
    main()
